/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Playtime': '游戏时长',
    'Shop': '商店',
    'Settings': '设置',
    'Skills': '技能',
    'Research': '研究',
    'Research all': '研究全部',
    'Researching Power': '研究力量',
    'Reset': '重置',
    'Shop Cost Multi': '商店成本倍数',
    'Statistics': '统计',
    'Upgrade +': '升级 +',
    'Upgrade': '升级',
    'Active Playtime': '在线游戏时间',
    'Achievements': '成就',
    'Auto Delete': '自动删除',
    'Basic': '基本',
    'Bank Account': '银行账户',
    'Buy': '购买',
    'button': '按钮',
    'Buy all': '全部购买',
    'Bonus': '奖励',
    'Copy': '复制',
    'Copy this and save it somewhere.': '复制此并将其保存在某处。',
    'Daily Reward': '日常奖励',
    'EXp Multi': '经验倍数',
    'EXP Multi': '经验倍数',
    'Export': '导出',
    'Font Loaded': '字体已加载',
    'Import': '导入',
    'Marketing Speed': '营销速度',
    'Marketing Power': '营销力量',
    'Making a name': '成名',
    'Get More': '获取更多',
    'Get your first fan': '得到你的第一个粉丝',
    'Good Game': '好游戏',
    'Hard Reset': '硬复位',
    'Ideas': '想法',
    'Level': '等级',
    'Load': '加载',
    'My first game!': '我的第一个游戏！',
    'Pause on Load': '暂停加载',
    'Pause on Recursion': '暂停递归',
    'Tapper GameDev Miner': '点击游戏开发矿工',
    'Version': '版本',
    'Bonus Shop': '奖励商店',
    'Bonus Points': '奖励点',
    'Bugs': '错误',
    'Free Stuff': '免费的东西',
    'Learn to Code': '学习编码',
    'Learn to Count': '学习计数',
    'Logician': '逻辑师',
    'Logic Exp Multi': '逻辑经验倍数',
    'Max. Retention': '最大保留',
    'Init.Players': '初始玩家',
    'Retention': '保留',
    'Tier': '层',
    'Think': '思考',
    'Ideas are needed to create game features': '创建游戏功能需要创意',
    'World Domination': '统治世界',
    'Wash your hair': '洗头发',
    'Unlocks Marketing': '解锁营销',
    'Unlocks Shop': '解锁商店',
    'Unlocks Features': '解锁功能',
    'Unlocks contracts': '解锁合同',
    'Unlocks butchering': '解锁屠宰',
    'Unlocks Bug fixing': '解锁错误修复',
    'Unlocks at level': '解锁等级',
    'Achievement Unlocked: I have an idea for a game': '成就解锁：我有一个游戏的想法',
    'Auto Release Threshold': '自动发布入口',
    'Bug Fixing Power': '错误修复力量',
    'Bug Fixing Speed': '错误修复速度',
    'Enable Game Plot': '启用游戏情节',
    'Enable Music': '启用音乐',
    'Earn your first cent': '赚取你的第一分钱',
    'Done!': '完成！',
    'Dev': '开发',
    'Exp Multi': '经验倍数',
    'Features': '功能',
    'Fans': '粉丝',
    'Fan gain per player': '每位玩家获得粉丝',
    'Fan gain per hour': '每小时粉丝获得',
    'Fan Expectations': '粉丝预期',
    'Finally it pays out!': '最后它付出了代价！',
    'Power': '力量',
    'Program': '编程',
    'Program 2 features': '编程 2 个功能',
    'Quality': '质量',
    'Quality Game': '优质游戏',
    'Reach Charisma Level': '达到魅力等级',
    'Release': '发布',
    'Reward: Unlocks Features; 5 Bonus Points': '奖励：解锁功能; 5奖励点',
    'Logic Points': '逻辑点',
    'Logic': '逻辑',
    'Need more ideas!': '需要更多想法！',
    'Changelog': '更新日志',
    'Charisma Exp Multi': '魅力经验加成',
    'Contractor': '承包商',
    'Charismatic': '超凡魅力Creative',
    'Creative': '创意',
    'Creativity': '创造力',
    'Creativity Exp Multi': '创造力经验加成',
    'Creativity Points': '创意点',
    'Credits': '鸣谢',
    'Day': '天',
    'Enable Sound': '启用声音',
    'Feature Programming': '功能编程',
    'Bulk Thinking': '整体思维',
    'Disclaimer': '免责声明',
    'Donations': '捐赠',
    'Great Ideas': '伟大的想法',
    'Holiday': '假日',
    'Holiday Discount': '假日折扣',
    'Reach Logic Level': '达到逻辑级别',
    'Reach Creativity Level': '达到创造力水平',
    'Reach Intelligence Level': '达到智力水平',
    'Replayability': '可玩性',
    'Thinking Power': '思考力量',
    'Thinking Speed': '思考速度',
    'Total Ideas': '想法总数',
    'Achievement Unlocked: What\'s that?': '成就解锁：那是什么？',
    'Reward: Unlocks Bug fixing; 5 Bonus Points': '奖励：解锁错误修复; 5奖励点',
    'Value': '值',
    'Volume': '音量',
    'What\'s that?': '那是什么？',
    'Quality Multi': '质量倍数',
    'Achievement Unlocked: Insect Killer': '解锁成就:昆虫杀手',
    'Fix': '修复',
    'Fix 10 bugs total': '修复10个错误',
    'Programming Power': '编程能力',
    'Programming turns ideas into features that improve the playtime and quality of your game': '编程将想法转化为能够提高游戏时间和质量的功能',
    'Passive Playtime': '被动游戏时间',
    'Paste the savedata here and click load.': '将存档数据粘贴到这里，然后单击加载按钮。',
    'Bugs decrease the quality of your games, so get rid of them!': '错误会降低游戏的质量，所以一定要清除它们!',
    'Publicity': '宣传',
    'Use Engineering Notation': '使用工程符号',
    'Unlocks Game tab': '解锁游戏标签',
    'Total Players': '总玩家',
    'Increases charisma skill learning speed by +10% per level (compounding': '每个级别增加+ 10％的魅力技能学习速度（复合',
    'Increases logic skill learning speed by +10% per level (compounding': '每级逻辑技能学习速度提高+ 10％（复合',
    'Increases the chance for great ideas by 10% per level (diminishing). Great Ideas turn into great features which give 10 quality': '每个级别增加10％的好主意（减少）。 伟大的想法变成伟大的功能，提供10质量',
    'Insect Killer': '昆虫杀手',
    'Intelligence Exp Multi': '智力经验倍数',
    'Intelligent': '智能',
    'Link': '链接',
    'max': '最大',
    'Multiplies ideas by 2 per level': '每个级别将想法乘以2',
    'Multiplies the cost of Holiday by 90% per level (diminishing': '每级增加90%的假期成本(递减)',
    'release': '发布',
    'Turn your Device': '开启设备',
    'Unlocks telescope research': '解锁望远镜研究',
    'Think of 1 K ideas in total': '想出总共1000个想法',
    'Think 2 times faster per level': '每级让思考快2倍',
    'Release a game with a playtime of 100 hours': '发布一款游戏，并且有100小时的玩游戏时间',
    'Release a game with a quality of at least': '发布一款最低质量的游戏',
    'Reward Available!': '奖励可用！',
    'Release your first game': '发布你的第一款游戏',
    'Great Features': '强大的功能',
    'Game made by': '游戏作者',
    'Value: +': '值: +',
    'Fix 1 K bugs total': '修复1000个Bug',
    'Coding Patterns': '编码模式',
    'Release a game with a retention of': '发布一个游戏保留',
    'Programming Speed': '编程速度',
    'Program 2 times faster per level': '每级使编程快2倍',
    'Produce fewer bugs per feature.': '每个功能产生的错误更少。',
    'Multiplies the influence a feature has on the programming power by 90% per level (diminishing': '将一个特性对编程能力的影响每级增加90%(递减)',
    'Multiplies Bandwidth cost by 95% per level (diminishing': '将带宽成本乘以每级95％（递减',
    'Multiplies bug fixing speed by 2 per level': '每个级别将错误修复速度乘以2',
    'Bug Fixing': '错误修复',
    'Careful Programming': '精心设计的编程',
    'Content Streching': '内容延伸',
    'Server Architecture': '服务器架构',
    'Server full! Delete a game in the game tab': '服务器满了！ 在游戏标签中删除一个游戏',
    'Increases playtime of games by 2.5 Min per feature per level': '每个级别的每个功能增加游戏的游戏时间2.5分钟',
    'I have an idea for a game': '我有一个游戏的想法',
    'Get daily rewards and unlock achievements to get more bonus points': '获得每日奖励和解锁成就，以获得更多奖励点',
    'Butcher all': '屠宰所有',
    'Follow me on Kongregate for 5 Bonus Points!': '在Kongregate上关注我获得5个奖励点！',
    'A great feature gives 10 quality': '一个伟大功能提供10质量',
    'Adds an option to buy 100 of each employee and butcher them, if affordable': '如果可以负担的话，添加一个选项来购买100名每位员工并屠宰他们',
    'Adds an option to buy all items in the shop with one click': '添加一个选项，只需点击一下即可购买商店中的所有商品',
    'Adds an option to buy all researches with one click': '添加一个选项，只需点击一下即可购买所有研究',
    'Adds an option to buy buffs automatically': '添加一个自动购买增益的选项',
    'Adds an option to delete games automatically when the server is full': '添加一个选项，在服务器已满时自动删除游戏',
    'Adds an option to release a contract automatically': '添加一个自动发布合同的选项',
    'Adds an option to release games automatically': '添加一个自动发布游戏的选项',
    'Adds an option to upgrade bandwidth automatically': '添加一个自动升级带宽的选项',
    'Auto Bandwidth': '自动带宽',
    'Auto Buff': '自动增益',
    'Auto Contract': '自动合同',
    'Auto Release': '自动发布',
    'Increase your learning speed by +100% per level': '每级提高学习速度+ 100％',
    'Ok': '好的',
    'Join the Subreddit for 5 Bonus Points!': '加入Subreddit获得5个奖励点！',
    'Join the Discord for 5 Bonus Points!': '加入Discord获得5个奖励点！',
    'Like me on Facebook for 5 Bonus Points!': '在Facebook上Like我，获得5个奖励点！',
    'Reset your Creativity Skills': '重置您的创造力技能',
    'Reset your Logic Skills': '重置您的逻辑技能',
    'Achievement Unlocked: My first game!': '成就解锁：我的第一款游戏！',
    'Max': '最大',
    'Reward: Unlocks Game tab; 5 Bonus Points': '奖励：解锁游戏标签; 5点奖励点',
    'Money': '金钱',
    'The amount of players that will play your game on release': '在发布时玩游戏的玩家数量',
    'The quality needed to get maximum retention': '获得最大保留所需的质量',
    'Your fans will play all of your new games when they release': '您的粉丝将在发布时玩您的所有新游戏',
    'Achievement Unlocked: Total Players': '成就解锁：玩家总数',
    'Get your games played 1k times in total': '让您的游戏总被玩次数达到1000次',
    'Market': '销售',
    'Games': '游戏',
    'Achievement Unlocked: Total Ideas': '成就解锁：总想法',
    'Hi Mom!': '嗨，妈妈！',
    'Reward: Creativity Exp Multi x1.02; 5 Bonus Points': '奖励：创意经验倍数x1.02; 5点奖励积分',
    'Think of 1k ideas in total': '总共想出1k个想法',
    'RPG Tap': 'RPG点击',
    'Charisma': '魅力',
    'Charisma Points': '魅力点',
    'Multiplies marketing speed by 2 per level': '每个级别的营销速度乘以2',
    '1% of the players of each game per level also play every other game': '每个级别每个游戏的玩家中有1％也玩其他游戏',
    '1000 fans will donate 0.02 per level every hour': '1000名粉丝每小时将捐赠0.02每级',
    'Brand Building': '品牌建设',
    'Band Width': '带宽',
    'Buy +': '购买 +',
    'Buffs': '增益',
    'Bubble Gum': '泡泡糖',
    'Calculator': '计算器',
    'Cent decoration': '装饰品',
    'Energy Drink': '能量饮料',
    'Extremely Tiny Computer': '微型计算机',
    'Coffee': '咖啡',
    'Achievement Unlocked: Bank Account': '解锁成就:银行账户',
    'Unlocks employees': '解锁员工',
    'Market your game to give it more publicity and reach more players': '推广您的游戏，为其提供更多宣传，并吸引更多玩家',
    'Achievement Unlocked: Charismatic': '成就解锁：魅力十足',
    'Multiplies shop prices by 95% per level (diminishing': '每个级别的商店价格乘以95％（递减',
    'Multiplies the price of employees by 95% per level (diminishing': '每级将员工价格乘以95％（递减',
    'Reset your Charisma Skills': '重置你的魅力技能',
    'Shop Discount': '商店折扣',
    'Think of 10 K ideas in total': '总共思考10 K个想法',
    'Money Grabbing': '抢钱',
    'Increases cpm by +10% per level (compounding': '每级cpm增加+ 10％（复合',
    'Great Ideas are needed to create great game features. A great feature gives 10 quality': '创造出色的游戏功能需要伟大想法。 一个伟大功能提供10质量',
    'Employee Discount': '员工折扣',
    'Items': '物品',
    'Learn 2 times faster for 4 minutes (affected by tickspeed': '4分钟学习速度提高2倍（受到tick速度的影响',
    'Learn Creativity 1.1 times faster': '学习创造力快1.1倍',
    'Hang the first cent you ever earned on the wall to get more Motivation and work 1.1 faster': '把你曾经赚到的第一分钱挂在墙上，以获得更多的动力并更快地工作，工作速度x1.1',
    'Employees': '员工',
    'Flea': '跳蚤',
    'Idea Guys': '有想法的人',
    'Marketers': '市场营销人员',
    'Bug Fixers': '错误修复者',
    'Feature Programmers': '功能程序员',
    'Not very pleasant to have around in the office. Power': '在办公室里到处走动不是很愉快。加油',
    'They are not really good in what they are doing but at least you can idle a bit. Power': '他们在做什么并不是很好，但至少你可以闲着一点。 加油',
    'Cockroach': '蟑螂',
    'How many games you can have published at the same time': '您可以同时发布多少个游戏',
    'How many players can play a game simultaneously': '有多少玩家可以同时玩游戏',
    'Server Size': '服务器大小',
    'Name': '名称',
    'Total Plays': '总游戏次数',
    'New Players': '新玩家',
    'Cactus': '仙人掌',
    'Megaphone': '扩音器',
    'Marketing Effectiveness': '营销效率',
    'Typewriter': '打字机',
    'Get new ideas 1.1 times faster': '获得新想法的速度提高1.1倍',
    'Learn 2 times faster for 20 minutes (affected by tickspeed': '20分钟内学习速度提高2倍（受tick速度影响',
    'Memorability': '记忆性',
    'Software Architecture': '软件架构',
    'Team Work': '团队合作',
    'Shitty Phone': '低劣的电话',
    'Programming Quality': '编程质量',
    'Achievement Unlocked: Logician': '成就解锁：逻辑师',
    'Tapper Idle': '点击放置',
    'Program new features 1.1 times faster': '编程新功能的速度提高了1.1倍',
    'Book': '书',
    'Cocaine': '可卡因',
    'Clash of Civ': '文明与冲突',
    'Employees get their power multiplied by 0.1% per level for each employee working on the same task': '对于从事同一任务的每位员工，员工的效率每级乘以0.1％',
    'Fix 10 K bugs total': '修复10 K错误',
    'Multiplies structuring speed by 2 per level (unlock through research': '将每个级别的结构化速度乘以2（通过研究解锁',
    'Multiplies the quality of a game by 2 per level': '每个级别将游戏质量乘以2',
    'Actions': '操作',
    'Delete': '删除',
    'Current Players': '当前玩家',
    'CPM (Money you get per 1000 Players': 'CPM (每千名玩家获得的金额',
    'Time since release': '发布后的时间',
    'Total Players (Amount of people that played your game at least once. If it equals the population, no new people will play': '总玩家数（至少玩过一次游戏的人数。如果等于人口，则不会有新玩家参与',
    'Total Revenue': '总收入',
    'Get your games played 10 Million times in total': '',
    'Marketing Efficiency': '营销效率',
    'Increases fan gain by +20% per level (compounding': '每级增加粉丝增益+ 20％（复合',
    'How long your game can be played without running out of content': '在没有内容耗尽的情况下，您的游戏可以玩多长时间',
    'Multiplies initial Players by 2 per level': '每个级别将初始玩家乘以2',
    'Multiplies marketing efficiency decay by 90% per level (diminishing': '将营销效率每个级别的衰减率提高90％（递减',
    'Tapper Incremental': '增量点击',
    'Ant Farm': '蚂蚁农场',
    'Research Bench': '研究工作台',
    'Achievement Unlocked: Quality Game': '解锁成就：高质量游戏',
    'Community Building': '社区建设',
    'Grow Tapper': '成长点击',
    'Tap Grind': '点击工匠',
    'Unlocks research': '解锁研究',
    'Clash Defence': '冲突防御',
    'Craft Tycoon': '工艺大亨',
    'Achievement Unlocked: Making a name': '成就解锁：成名',
    'Reward: Unlocks contracts; 5 Bonus Points': '奖励：解锁合同; 5点奖励点',
    'Fix Bugs 1.1 times faster': '修复错误速度x1.1倍',
    'Haircut': '理发',
    'Learn everything 1.1 times faster': '学习一切快了1.1倍',
    'Learn logic 1.1 times faster': '学习逻辑的速度提高1.1倍',
    'Market 1.1 times faster': '市场增长x1.1倍',
    'Better Calculator': '更好的计算器',
    'Better Book': '更好的书',
    'Better Decoration': '更好的装饰',
    'Company: Generica': '公司：通用',
    'Company: Eviltronic Arts': '公司：恶魔艺术',
    'Contracts': '合同',
    'Contracts will give you special rewards if you fulfill them. You need to accept a contract to work on it. The game created will not belong to you, so won\'t bring you revenue or fans. You will only get the reward.': '如果您履行合同，合同将给予您特殊奖励。 您需要接受合同才能使用它。 创建的游戏不属于您，因此不会为您带来收入或粉丝。 你只会获得奖励。',
    'Create a game with a quality of': '创建一个游戏质量为',
    'Hello World!': '你好，世界！',
    'Learn creativity 1.1 times faster': '学习创造力快1.1倍',
    'Miner Idle': '矿工放置',
    'Repeatable': '重复',
    'Reward: ?': '奖励: ?',
    'Special': '特殊',
    'To the dark side': '黑暗的一面',
    'Yes': '是',
    'No': '否',
    'Accept': '同意',
    '1k Fans needed': '需要1k粉丝',
    'Titans Inc.': '泰坦公司',
    'Cancel': '取消',
    'Better Style': '更好的风格',
    'Reward': '奖励',
    'Clash of Pixel Incremental': '像素增量冲突',
    'Chopper Idle': '砍树放置',
    'Company: Your fanclub': '公司：你的粉丝俱乐部',
    'Create a game with a playtime of 0 and a quality of 1.31k.': '创建游戏时间为0且质量为1.31k的游戏。',
    'Refresh your thoughts. Will reset the cost of new ideas. (Use when getting ideas is slowing down': '刷新你的想法。 将重置新想法的成本。 （在获得想法时放慢使用',
    'Achievement Unlocked: Replayability': '成就解锁：可重玩性',
    'Better Bug Pets': '更好的错误宠物',
    'Better Haircut': '更好的理发',
    'Better PC': '更好的电脑',
    'Better Typewriter': '更好的打字机',
    'Think of new ideas 1.1 times faster': '思考新想法的速度要快1.1倍',
    'Learn charisma 1.1 times faster': '学习魅力的速度要快1.1倍',
    'Miner Incremental': '矿工增量',
    'Meth': '冰毒',
    'Fix bugs 1.1 times faster': '修复bug的速度提高了1.1倍',
    'Intelligence Points': '智力点',
    'Release a game with a playtime of 1 K hours': '发布一个游戏时间为1k小时',
    'Research Points': '研究点',
    'Scientists': '科学家',
    'Intelligence': '智力',
    'At least they are cute. Power': '至少它们很可爱。加油',
    'Hamster': '仓鼠',
    'Research new technologies to make your games better': '研究新技术使你的游戏更好',
    'The percentage of players that can keep playing every hour based on playtime': '根据游戏时间，玩家每小时可以继续玩游戏的百分比',
    'The percentage of players that will keep playing every hour based on playtime and quality/expecations': '基于游戏时间和质量/期望，玩家每小时坚持玩游戏的百分比',
    'Money you will get for 1000 plays': '每1000个玩家你可以得到的钱',
    'How good your game is': '你的游戏有多好',
    'Increases buff duration by 20% per level': '每级增加增益持续时间20％',
    'Increases creativity learning speed by +10% per level (compounding': '每级增加+ 10％的创造力学习速度（复合',
    'Learn to think': '学会思考',
    'Multiplies the price of researches by 95% per level (diminishing': '研究价格每级增加95％（递减',
    'Research Discount': '研究折扣',
    'Reset your Intelligence Skills': '重置您的智力技能',
    'The money your fans give you every hour': '你的粉丝每小时给你的钱',
    'Chemistry': '化学',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'fixed: great feature enabling not saving': '修复：伟大功能不能保存',
    'fixed: holiday and party affected by buyamount': '已修复：假日和受到买方影响的一方',
    'fixed: players of a game directly becoming': '修正：直接成为游戏的玩家',
    'fixed: power multi of employees not displayed': '修复：员工的功率倍数不显示',
    'added: holiday and party for money': '添加：假期和派对换钱',
    'added: checkbox to enable programming for great and unique features': '添加：复选框以启用优秀和独特功能的编程',
    'added: auto release threshold setting': '添加：自动释放阈值设置',
    '': '',
    '': '',
    '\n                               You have to release your game before starting the contract. Release now?                          ': '您必须在开始合同之前发布您的游戏。 现在发布？',
    '\n                               You have to release your game before starting the contract. But your server is full. Do you want to abandon your game? YOUR CURRENT GAME WILL BE ABANDONED AND NOT RELEASED IF YOU CLICK YES                          ': '你必须在开始合同之前释放你的游戏。 但是你的服务器已满。 你想放弃你的游戏吗？ 如果您点击是，您的当前游戏将被放弃并且不会被释放',
    '\n                               Thank you!                          ': '非常感谢！',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^(\d+)h Bonus Seconds$/, '$1小时奖励时间'],
    [/^Work (\d+) times faster for (\d+) minutes \(affected by tickspeed$/, '以$1倍的速度工作$2分钟\(受tickspeed影响)'],
    [/^Get (\d+) hour of Bonus seconds \((\d+)x speed for$/, '获得$1小时奖励时间 \($2倍速度持续'],
    [/^Get (\d+) hours of Bonus seconds \((\d+)x speed for (\d+)h hours$/, '获得$1小时奖励时间 \($2 倍速度持续 $3 小时'],
    [/^Cost: (\d+) Bonus Points$/, '成本: $1 奖励点'],
    [/^Cost: (\d+) Intelligence Points$/, '成本: $1 智力点'],
    [/^Cost: (\d+) Charisma Points$/, '成本: $1 魅力点'],
    [/^Cost: ([\d\.]+) Money$/, '成本: $1 金钱'],
    [/^Cost: ([\d\.]+)k Money$/, '成本: $1k 金钱'],
    [/^Cost: (\d+) Logic Points$/, '成本: $1 逻辑点'],
    [/^Cost: (\d+) Creativity Points$/, '成本:$1 创意点'],
    [/^Get ([\d\.]+)(.+) fans$/, '获得 $1$2 粉丝'],
    [/^Have ([\d\.]+) K money$/, '有 $1K 块钱'],
    [/^Have ([\d\.]+) money$/, '有 $1 块钱'],
    [/^Have ([\d\.]+) research points$/, '有 $1 研究点'],
    [/^Have ([\d\.]+) ideas$/, '有 $1 想法'],
    [/^Have ([\d\.]+) fleas$/, '有 $1 跳蚤'],
    [/^Level: (\d+) \/$/, '等级：$1 \/'],
    [/^Get your games played ([\d\.]+) K times in total$/, '让您的游戏总被玩次数达到$1 K次'],
    [/^(\d+) Money$/, '$1 块钱'],
    [/^Games: (\d+)\/$/, '游戏：$1\/'],
    [/^Next Reward: (\d+)h(\d+)m$/, '下一个奖励：$1h$2m'],
    [/^(\d+) Bonus Points$/, '$1 奖励点'],
    [/^(\d+) BP$/, '$1 奖励点'],
    [/^(\d+) Unemployed$/, '$1 失业者'],
    [/^Release a game with a quality of at least (\d+) K$/, '发布一款质量至少为 $1 K的游戏'],
    [/^Version: (\d+).$/, '版本号：$1.'],
    [/^Reward: (\d+) Money$/, '奖励：$1 金钱'],
    [/^Reward: ([\d\.]+) Fans$/, '奖励：$1 粉丝'],
    [/^Time to accept: (\d+)m$/, '剩余同意时间：$1m'],
    [/^Reward: ([\d\.]+) Fans$/, '奖励：$1 粉丝'],
    [/^Release (\d+) contracts in total$/, '共发布 $1 份合同'],
    [/^Reward: Feature Programming x([\d\.]+); ([\d\.]+) Bonus Points$/, '奖励：功能编程x$1; $2点奖励点'],
    [/^Reward: Marketing Speed x([\d\.]+); ([\d\.]+) Bonus Points$/, '奖励：营销速度x$1; $2点奖励点'],
    [/^Reward: Charisma Exp Multi x([\d\.]+); ([\d\.]+) Bonus Points$/, '奖励:魅力经验倍数 x$1；$2奖励点'],
    [/^Reward: Logic Exp Multi x([\d\.]+); ([\d\.]+) Bonus Points$/, '奖励:逻辑经验倍数 x$1；$2奖励点'],
    [/^Reward: Bug Fixing Speed x([\d\.]+); ([\d\.]+) Bonus Points$/, '奖励:错误修复速度x$1；$2奖励点'],
    [/^Reward: Intelligence Exp Multi x([\d\.]+); ([\d\.]+) Bonus Points$/, '奖励：智力经验倍数x$1；$2点奖励点'],
    [/^\n                               You got (\d+) Bonus Points! Come back tomorrow for more!                          $/, '你得到$1点奖励点！ 明天再来可以获得更多！'],
    [/^Time: (\d+) Years, (\d+) Days, (\d+) Hours,$/, '时间：$1年，$2天，$3小时，'],
    

]);