/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Playtime': '游戏时长',
    'Shop': '商店',
    'Settings': '设置',
    'Skills': '技能',
    'Research': '研究',
    'Research all': '研究全部',
    'Researching Power': '研究力量',
    'Reset': '重置',
    'Shop Cost Multi': '商店成本倍数',
    'Statistics': '统计',
    'Upgrade +': '升级 +',
    'Upgrade': '升级',
    'Active Playtime': '在线游戏时间',
    'Achievements': '成就',
    'Auto Delete': '自动删除',
    'Basic': '基本',
    'Bank Account': '银行账户',
    'Buy': '购买',
    'button': '按钮',
    'Buy all': '全部购买',
    'Bonus': '奖励',
    'Copy': '复制',
    'Copy this and save it somewhere.': '复制此并将其保存在某处。',
    'Daily Reward': '日常奖励',
    'EXp Multi': '经验倍数',
    'EXP Multi': '经验倍数',
    'Export': '导出',
    'Font Loaded': '字体已加载',
    'Import': '导入',
    'Marketing Speed': '营销速度',
    'Marketing Power': '营销力量',
    'Making a name': '做个名字',
    'Get More': '获取更多',
    'Get your first fan': '得到你的第一个粉丝',
    'Get your games played 1 K times in total': '让您的游戏被玩的次数累计达到1000次',
    'Good Game': '好游戏',
    'Hard Reset': '硬复位',
    'Ideas': '想法',
    'Level': '等级',
    'Load': '加载',
    'My first game!': '我的第一个游戏！',
    'Pause on Load': '暂停加载',
    'Pause on Recursion': '暂停递归',
    'Tapper GameDev Miner': '点击游戏开发矿工',
    'Version': '版本',
    'Bonus Shop': '奖励商店',
    'Bonus Points': '奖励点',
    'Bugs': '错误',
    'Free Stuff': '免费的东西',
    'Learn to Code': '学习编码',
    'Learn to Count': '学习计数',
    'Logician': '逻辑学家',
    'Logic Exp Multi': '逻辑经验倍数',
    'Max. Retention': '最大保留',
    'Init.Players': '初始玩家',
    'Retention': '保留',
    'Tier': '层',
    'Think': '思考',
    'Ideas are needed to create game features': '创建游戏功能需要创意',
    'World Domination': '统治世界',
    'Wash your hair': '洗头发',
    'Unlocks Marketing': '解锁营销',
    'Unlocks Shop': '解锁商店',
    'Unlocks Features': '解锁功能',
    'Unlocks contracts': '解锁合同',
    'Unlocks butchering': '解锁屠宰',
    'Unlocks Bug fixing': '解锁错误修复',
    'Unlocks at level': '解锁等级',
    'Achievement Unlocked: I have an idea for a game': '成就解锁：我有一个游戏的想法',
    'Auto Release Threshold': '自动发布入口',
    'Bug Fixing Power': '错误修复力量',
    'Bug Fixing Speed': '错误修复速度',
    'Enable Game Plot': '启用游戏情节',
    'Enable Music': '启用音乐',
    'Earn your first cent': '赚取你的第一分钱',
    'Done!': '完成！',
    'Dev': '开发',
    'Exp Multi': '经验倍数',
    'Features': '功能',
    'Fans': '粉丝',
    'Fan gain per player': '每位玩家获得粉丝',
    'Fan gain per hour': '每小时粉丝获得',
    'Fan Expectations': '粉丝预期',
    'Finally it pays out!': '最后它付出了代价！',
    'Power': '力量',
    'Program': '编程',
    'Program 2 features': '编程 2 个功能',
    'Quality': '质量',
    'Quality Game': '优质游戏',
    'Reach Charisma Level': '达到魅力等级',
    'Release': '发布',
    'Reward: Unlocks Features; 5 Bonus Points': '奖励：解锁功能; 5奖励点',
    'Logic Points': '逻辑点',
    'Logic': '逻辑',
    'Need more ideas!': '需要更多想法！',
    'Changelog': '更新日志',
    'Charisma Exp Multi': '魅力经验加成',
    'Contractor': '承包商',
    'Charismatic': '超凡魅力Creative',
    'Creative': '创意',
    'Creativity': '创造力',
    'Creativity Exp Multi': '创造力经验加成',
    'Creativity Points': '创意点',
    'Credits': '鸣谢',
    'Day': '天',
    'Enable Sound': '启用声音',
    'Feature Programming': '功能编程',
    'Bulk Thinking': '整体思维',
    'Disclaimer': '免责声明',
    'Donations': '捐赠',
    'Great Ideas': '伟大的想法',
    'Holiday': '假日',
    'Holiday Discount': '假日折扣',
    'Reach Logic Level': '达到逻辑级别',
    'Reach Creativity Level': '达到创造力水平',
    'Reach Intelligence Level': '达到智力水平',
    'Replayability': '可玩性',
    'Thinking Power': '思考力量',
    'Thinking Speed': '思考速度',
    'Total Ideas': '想法总数',
    'Achievement Unlocked: What\'s that?': '成就解锁：那是什么？',
    'Reward: Unlocks Bug fixing; 5 Bonus Points': '奖励：解锁错误修复; 5奖励点',
    'Value': '值',
    'Volume': '音量',
    'What\'s that?': '那是什么？',
    'Quality Multi': '质量倍数',
    'Achievement Unlocked: Insect Killer': '解锁成就:昆虫杀手',
    'Fix': '修复',
    'Fix 10 bugs total': '修复10个错误',
    'Reward: Bug Fixing Speed x1.01; 5 Bonus Points': '奖励:错误修复速度x1.01；5奖励点',
    'Programming Power': '编程能力',
    'Programming turns ideas into features that improve the playtime and quality of your game': '编程将想法转化为能够提高游戏时间和质量的功能',
    'Passive Playtime': '被动游戏时间',
    'Paste the savedata here and click load.': '将存档数据粘贴到这里，然后单击加载按钮。',
    'Bugs decrease the quality of your games, so get rid of them!': '错误会降低游戏的质量，所以一定要清除它们!',
    'Publicity': '宣传',
    'Use Engineering Notation': '使用工程符号',
    'Unlocks Game tab': '解锁游戏标签',
    'Total Players': '总玩家',
    'Increases charisma skill learning speed by +10% per level (compounding': '每个级别增加+ 10％的魅力技能学习速度（复合',
    'Increases logic skill learning speed by +10% per level (compounding': '每级逻辑技能学习速度提高+ 10％（复合',
    'Increases the chance for great ideas by 10% per level (diminishing). Great Ideas turn into great features which give 10 quality': '每个级别增加10％的好主意（减少）。 伟大的想法变成伟大的功能，提供10质量',
    'Insect Killer': '昆虫杀手',
    'Intelligence Exp Multi': '智力经验倍数',
    'Intelligent': '智能',
    'Link': '链接',
    'max': '最大',
    'Multiplies ideas by 2 per level': '每个级别将想法乘以2',
    'Multiplies the cost of Holiday by 90% per level (diminishing': '每级增加90%的假期成本(递减)',
    'release': '发布',
    'Turn your Device': '开启设备',
    'Unlocks telescope research': '解锁望远镜研究',
    'Think of 1 K ideas in total': '想出总共1000个想法',
    'Think 2 times faster per level': '每级让思考快2倍',
    'Release 1 contracts in total': '共发布1份合同',
    'Release a game with a playtime of 100 hours': '发布一款游戏，并且有100小时的玩游戏时间',
    'Release a game with a quality of at least': '发布一款最低质量的游戏',
    'Reward Available!': '奖励可用！',
    'Release your first game': '发布你的第一款游戏',
    'Great Features': '强大的功能',
    'Game made by': '游戏作者',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'added: auto release threshold setting': '添加：自动释放阈值设置',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '\n                               You got 1 Bonus Points! Come back tomorrow for more!                          ': '你得到1点奖励点！ 明天再来可以获得更多！',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Cost: (\d+) Bonus Points$/, '成本: $1 奖励点'],
    [/^Get ([\d\.]+)(.+) fans$/, '获得 $1$2 粉丝'],
    [/^Have ([\d\.]+) money$/, '有 $1 块钱'],
    [/^Have ([\d\.]+) ideas$/, '有 $1 想法'],
    [/^Have ([\d\.]+) fleas$/, '有 $1 跳蚤'],
    [/^Level: (\d+) \/$/, '等级：$1 \/'],
    [/^(\d+) Money$/, '$1 块钱'],
    [/^(\d+) Bonus Points$/, '$1 奖励点'],
    [/^Time: (\d+) Years, (\d+) Days, (\d+) Hours,$/, '时间：$1年，$2天，$3小时，'],
    
    [/^Cost: (\d+) Creativity Points$/, '成本:$1 创意点'],

]);